name: Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libsqlite3-dev
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Install gems
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bundle exec rubocop --parallel
    - name: Prepare to RSpec
      run: bundle exec rake db:create db:schema:load RAILS_ENV=test
    - name: Run RSpec
      run: bundle exec rspec
